language: python

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments

script:
    - hugo



    # Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 0ce3803511c598b2a31872c57809a3ec42ca28ff
  local_dir: public
  on:
    branch: master